# 应用名称
spring:
  application:
    name: yanchao_springboot
    # 数据库驱动：
  datasource:
    druid:
      password: 123456
      url: jdbc:mysql://localhost:3306/yan_chao?serverTimezone=UTC&characterEncoding=utf-8
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      #文件上传相关
      max-file-size: 3MB
      max-request-size: 3MB
  mail:
    host: smtp.qq.com
    port: 587
    username: 1542106578@qq.com
    password: ycjpzhzhmseihbfb
    default-encoding: utf-8
    properties:
      mail:
        stmp:
          socketFactory:
           class: javax.net.ssl.SSLSocketFactory
           port: 587
        debug: true
  #   redis相关配置
#  redis:
#    host: 43.138.105.124
#    port: 6379
#    password: 000415
#    database: 1
  redis:
    host: 192.168.204.129
    port: 6379
    password: 212412
    database: 14

    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0
        max-wait: 100ms
  # 静态资源对外暴露配置

server:
#    port: 80
  # 默认访问端口443。作用：访问https时，不需要添加端口443： https://域名
  # 例如：”port: 8443“ 时，https访问时，需要添加端口8443： https://域名:8443
  port: 443
#  ssl:
#    # resources根目录的”证书源文件.pfx“
#    key-store: classpath:520oo.jks
#    # “.pfx”证书对应格式，“.jks"证书对应“RSA”
#    key-store-type: JKS
#    # ”.txt“证书密码
#    key-store-password: 4fp794804h87
#    key-alias: ysunest.cn
#    enabled: true
  #下面这些内容是为了让MyBatis映射
  #指定Mybatis的Mapper文件
# mybatis.mapper-locations=classpath:mappers/*xml
mybatis:
  #mapper-default-scope: classpath:com.hunzhizi.dao.*
  #指定Mybatis的实体目录
  type-aliases-package: com.hunzhizi.domain
  configuration-properties:
    use-generated-keys: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: ${mybatis.configuration-properties.map-underscore-to-camel-case}
    useGeneratedKeys: ${mybatis.configuration-properties.use-generated-keys}

#分页插件

pagehelper:
  params: count=countSql
  reasonable: true
  support-methods-arguments: true






